<?php

return [
    'ide'     => 'vscode',
    'preset'  => 'default',
    'exclude' => [
        //  'path/to/directory-or-file'
    ],
    'add' => [
        // ExampleMetric::class => [
        //     ExampleInsight::class,
        // ]
    ],
    'remove' => [
        // Code
        \NunoMaduro\PhpInsights\Domain\Sniffs\ForbiddenSetterSniff::class,
        \ObjectCalisthenics\Sniffs\Metrics\MaxNestingLevelSniff::class,
        \ObjectCalisthenics\Sniffs\NamingConventions\ElementNameMinimalLengthSniff::class,
        \PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\ForLoopWithTestFunctionCallSniff::class,
        \PhpCsFixer\Fixer\Alias\NoMixedEchoPrintFixer::class,
        \PhpCsFixer\Fixer\ArrayNotation\NoMultilineWhitespaceAroundDoubleArrowFixer::class,
        \PhpCsFixer\Fixer\ArrayNotation\NormalizeIndexBraceFixer::class,
        \PhpCsFixer\Fixer\CastNotation\NoShortBoolCastFixer::class,
        \PhpCsFixer\Fixer\CastNotation\ShortScalarCastFixer::class,
        \PhpCsFixer\Fixer\ClassNotation\ProtectedToPrivateFixer::class,
        \PhpCsFixer\Fixer\ClassNotation\VisibilityRequiredFixer::class,
        \PhpCsFixer\Fixer\Comment\MultilineCommentOpeningClosingFixer::class,
        \PhpCsFixer\Fixer\Comment\NoEmptyCommentFixer::class,
        \PhpCsFixer\Fixer\ControlStructure\NoAlternativeSyntaxFixer::class,
        \PhpCsFixer\Fixer\ControlStructure\NoBreakCommentFixer::class,
        \PhpCsFixer\Fixer\ControlStructure\NoSuperfluousElseifFixer::class,
        \PhpCsFixer\Fixer\ControlStructure\NoUnneededControlParenthesesFixer::class,
        \PhpCsFixer\Fixer\ControlStructure\NoUselessElseFixer::class,
        \PhpCsFixer\Fixer\FunctionNotation\CombineNestedDirnameFixer::class,
        \PhpCsFixer\Fixer\FunctionNotation\NoSpacesAfterFunctionNameFixer::class,
        \PhpCsFixer\Fixer\FunctionNotation\VoidReturnFixer::class,
        \PhpCsFixer\Fixer\LanguageConstruct\DeclareEqualNormalizeFixer::class,
        \PhpCsFixer\Fixer\Operator\NewWithBracesFixer::class,
        \PhpCsFixer\Fixer\Operator\NewWithBracesFixer::class,
        \PhpCsFixer\Fixer\Operator\ObjectOperatorWithoutWhitespaceFixer::class,
        \PhpCsFixer\Fixer\Operator\TernaryOperatorSpacesFixer::class,
        \PhpCsFixer\Fixer\Operator\TernaryToNullCoalescingFixer::class,
        \PhpCsFixer\Fixer\Phpdoc\PhpdocScalarFixer::class,
        \PhpCsFixer\Fixer\ReturnNotation\ReturnAssignmentFixer::class,
        \PhpCsFixer\Fixer\StringNotation\ExplicitStringVariableFixer::class,
        \SlevomatCodingStandard\Sniffs\Classes\DisallowLateStaticBindingForConstantsSniff::class,
        \SlevomatCodingStandard\Sniffs\ControlStructures\DisallowEmptySniff::class,
        \SlevomatCodingStandard\Sniffs\ControlStructures\DisallowYodaComparisonSniff::class,
        \SlevomatCodingStandard\Sniffs\Operators\DisallowEqualOperatorsSniff::class,
        \SlevomatCodingStandard\Sniffs\PHP\UselessParenthesesSniff::class,
        \SlevomatCodingStandard\Sniffs\TypeHints\DeclareStrictTypesSniff::class,
        \SlevomatCodingStandard\Sniffs\TypeHints\DisallowArrayTypeHintSyntaxSniff::class,
        \SlevomatCodingStandard\Sniffs\TypeHints\DisallowMixedTypeHintSniff::class,
        \SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSniff::class,
        \SlevomatCodingStandard\Sniffs\TypeHints\PropertyTypeHintSniff::class,
        \SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff::class,

        // Architecture
        \NunoMaduro\PhpInsights\Domain\Insights\ForbiddenNormalClasses::class,
        \NunoMaduro\PhpInsights\Domain\Insights\ForbiddenTraits::class,
        \ObjectCalisthenics\Sniffs\Files\ClassTraitAndInterfaceLengthSniff::class,
        \ObjectCalisthenics\Sniffs\Metrics\MethodPerClassLimitSniff::class,
        \ObjectCalisthenics\Sniffs\Metrics\PropertyPerClassLimitSniff::class,
        \PhpCsFixer\Fixer\FunctionNotation\MethodArgumentSpaceFixer::class,
        \SlevomatCodingStandard\Sniffs\Classes\SuperfluousTraitNamingSniff::class,

        // Style
        \PHP_CodeSniffer\Standards\Generic\Sniffs\Files\LineEndingsSniff::class,
        \PHP_CodeSniffer\Standards\Generic\Sniffs\Files\LineLengthSniff::class,
        \PHP_CodeSniffer\Standards\PSR12\Sniffs\Classes\ClassInstantiationSniff::class,
        \PhpCsFixer\Fixer\ArrayNotation\NoTrailingCommaInSinglelineArrayFixer::class,
        \PhpCsFixer\Fixer\ArrayNotation\NoWhitespaceBeforeCommaInArrayFixer::class,
        \PhpCsFixer\Fixer\Basic\BracesFixer::class,
        \PhpCsFixer\Fixer\Basic\EncodingFixer::class,
        \PhpCsFixer\Fixer\Casing\LowercaseStaticReferenceFixer::class,
        \PhpCsFixer\Fixer\Casing\MagicConstantCasingFixer::class,
        \PhpCsFixer\Fixer\Casing\MagicMethodCasingFixer::class,
        \PhpCsFixer\Fixer\Casing\NativeFunctionCasingFixer::class,
        \PhpCsFixer\Fixer\Casing\NativeFunctionTypeDeclarationCasingFixer::class,
        \PhpCsFixer\Fixer\CastNotation\CastSpacesFixer::class,
        \PhpCsFixer\Fixer\ClassNotation\ClassDefinitionFixer::class,
        \PhpCsFixer\Fixer\ClassNotation\NoBlankLinesAfterClassOpeningFixer::class,
        \PhpCsFixer\Fixer\ClassNotation\OrderedClassElementsFixer::class,
        \PhpCsFixer\Fixer\ClassNotation\SingleClassElementPerStatementFixer::class,
        \PhpCsFixer\Fixer\Comment\NoTrailingWhitespaceInCommentFixer::class,
        \PhpCsFixer\Fixer\ControlStructure\SwitchCaseSemicolonToColonFixer::class,
        \PhpCsFixer\Fixer\ControlStructure\SwitchCaseSpaceFixer::class,
        \PhpCsFixer\Fixer\FunctionNotation\FunctionDeclarationFixer::class,
        \PhpCsFixer\Fixer\FunctionNotation\FunctionTypehintSpaceFixer::class,
        \PhpCsFixer\Fixer\Import\OrderedImportsFixer::class,
        \PhpCsFixer\Fixer\Import\SingleImportPerStatementFixer::class,
        \PhpCsFixer\Fixer\Operator\BinaryOperatorSpacesFixer::class,
        \PhpCsFixer\Fixer\Operator\StandardizeNotEqualsFixer::class,
        \PhpCsFixer\Fixer\Phpdoc\AlignMultilineCommentFixer::class,
        \PhpCsFixer\Fixer\Phpdoc\PhpdocIndentFixer::class,
        \PhpCsFixer\Fixer\Phpdoc\PhpdocInlineTagFixer::class,
        \PhpCsFixer\Fixer\Phpdoc\PhpdocTrimFixer::class,
        \PhpCsFixer\Fixer\Phpdoc\PhpdocVarAnnotationCorrectOrderFixer::class,
        \PhpCsFixer\Fixer\PhpTag\FullOpeningTagFixer::class,
        \PhpCsFixer\Fixer\Semicolon\NoSinglelineWhitespaceBeforeSemicolonsFixer::class,
        \PhpCsFixer\Fixer\StringNotation\SingleQuoteFixer::class,
        \PhpCsFixer\Fixer\Whitespace\MethodChainingIndentationFixer::class,
        \PhpCsFixer\Fixer\Whitespace\NoExtraBlankLinesFixer::class,
        \PhpCsFixer\Fixer\Whitespace\NoSpacesAroundOffsetFixer::class,
        \PhpCsFixer\Fixer\Whitespace\NoSpacesInsideParenthesisFixer::class,
        \PhpCsFixer\Fixer\Whitespace\NoTrailingWhitespaceFixer::class,
        \PhpCsFixer\Fixer\Whitespace\NoWhitespaceInBlankLineFixer::class,
        \PhpCsFixer\Fixer\Whitespace\SingleBlankLineAtEofFixer::class,
        \SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff::class,
    ],
    'config' => [
        // Architecture
        \ObjectCalisthenics\Sniffs\Files\FunctionLengthSniff::class => [
            'maxLength' => 55,
        ],

        // Complexity
        \NunoMaduro\PhpInsights\Domain\Insights\CyclomaticComplexityIsHigh::class => [
            'maxComplexity' => 45,
        ],
    ],
];
