name: compatibility

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        laminas-mvc: ['3.2.x-dev', '4.0.x-dev']

    name: laminas-mvc ${{ matrix.laminas-mvc }} compatibility

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/setup-php-action#cache-composer-dependencies
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laminas/laminas-mvc:${{ matrix.laminas-mvc }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction
