name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      # https://github.com/marketplace/actions/setup-php-action#cache-composer-dependencies
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install PHP 7 dependencies
        uses: nick-invision/retry@v1
        if: "matrix.php < 8"
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
              composer -V
              composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Install PHP 8 dependencies
        uses: nick-invision/retry@v1
        if: "matrix.php >= 8"
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
              composer -V
              composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --ignore-platform-reqs

      - name: Execute tests
        run: ./vendor/bin/phpunit
